name: "Update"
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"
jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell -E 'let flake = import ./. {}; in (import "${flake.inputs.nixpkgs}/maintainers/scripts/update.nix") { include-overlays = [flake.overlays.default]; package = "perforator"; skip-prompt = "true"; }' --show-trace
    - uses: stefanzweifel/git-auto-commit-action@v5
